# Generated by Django 5.2.15 on 2026-06-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Technical', 'Technical Courses'), ('Basic', 'Basic Courses'), ('Non-Technical', 'Non-Technical Courses'), ('Graphic Designing', 'Graphic Designing Courses'), ('Development Services', 'Development Services')], default='Technical', max_length=50),
        ),
    ]
