# Generated by Django 5.2.15 on 2026-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategenerationjob',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
