# Generated by Django 5.2.15 on 2026-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_add_fields_to_generation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategenerationjob',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
