# Generated by Django 5.2.15 on 2026-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_add_course_name_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
