# Generated by Django 5.2.15 on 2026-06-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_add_course_name_to_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificategenerationjob',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certificategenerationjob',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
