# Generated by Django 5.2.15 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_certificategenerationjob_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificategenerationjob",
            name="issue_date",
            field=models.CharField(max_length=50),
        ),
    ]
