# Generated by Django 5.2.15 on 2026-06-16 07:54

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_course_from_student'),
        ('certificates', '0006_increase_generation_job_issue_date_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateView',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='certificates.certificate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_views', to='accounts.student')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('certificate', 'student')},
            },
        ),
    ]
